name: CI

on:
  workflow_dispatch:
  push:
    branches: [ develop, main ]
    tags: [ v* ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        python_version: ['3.10','3.11']

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install libxmlsec1-dev pkg-config

      - name: Run build action
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/poetry-install@main
        with:
          python_version: ${{ matrix.python_version }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"
      
      - name: npm audit
        run: npm audit
    
      - name: npm ci
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

      - name: npm run build
        run: npm run build

      - name: Setup config
        run: |
          make setup-config
          make setup-saml
          make setup-secrets

      - name: Linting (pylint & black)
        run: make check

      - name: Typing (mypy)
        run: make type-check

      - name: Audit (bandit)
        run: make audit

      - name: Unit testing (pytest)
        run: make test

      - name: Run SonarCloud scanner
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/sonarcloud@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
